### ISSUE TITLE
User logged in/out only on current tab

### ISSUE THREAD

**Issue by joseluismurillorios** [samuelgozi/firebase-auth-lite#14]
When a user logs in and out, the ```listen``` function only triggers in current tab, am I missing something? I'm a beginner, adding this code to the ```Auth``` constructor seems to work for me, but I don't know if there is a better way to have all tabs synchronized. Thanks in advance

```
window.addEventListener('storage', (event) => {
    const key = `Auth:User:${apiKey}:${name}`;
    if (event.key === key) {
        this.storage.get(key).then(user => {
            if (user) {
                this.user = JSON.parse(user);
                this.fetchProfile();
            } else {
                this.user = null;
                this.emit();
            }
        });
    }
}, false);
```

**Comment by samuelgozi** [comment]
Thank you for taking the time to submit an issue.
You are not missing anything, I haven't thought of this scenario.
your solution seems to be a good one, but just to be sure I'll check if there is a better alternative.

**Comment by samuelgozi** [comment]
I just finished fixing this and pushed the changes in version `0.6.3`.
If you have any other issues/suggestions, please let me know.
