### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by aidarkhanov** [samuelgozi/firebase-auth-lite#16]
Hello, I want to thank you for creating this incredible library!

I have a question regarding initialization. What is the alternative way to use `onAuthStateChanged` in `firebase-auth-lite`? I am aware of existing `listen` method but it is not run if a user is not signed in nor interacted with `firebase-auth-lite`. More clearly, here is how I use `listen`:

```javascript
// firebase.js
import { isLoading, user } from "./store"

export function initializeFirebase() {
  auth.listen(res => {
    if (res) {
      isLoading.set(false)
      user.set(res)
    }
    isLoading.set(false)
  })
}

// App.svelte
import { initializeFirebase } from "./firebase"
import { isLoading } from "./store"

onMount(() => {
  initializeFirebase()
})

{#if $isLoading}
  <p>Loading...</p>
{:else}
  <h1>The main content</h1>
{/if}
```

In this case, `isLoading` variable is always set to `true`. I want for `initializeFirebase` to always run on page load despite user has or has not interacted with `firebase-auth-lite`. Thank you!

**Comment by samuelgozi** [comment]
Hi, Thank you for taking the time to submit an issue.
So you want to make an indicator that will be true if the Auth library is still trying to get the logged-in user?

I will update the library to call the listeners once it has been initialized and update once it's ready.
Please let me know If I didn't understand your intentions.

**Comment by samuelgozi** [comment]
Just published version `0.7.0`, In it, the listeners will be called on initialization when the user is not logged in too.

If the user is not logged in, the return value will be `null`.
Please let me know if there are any more issues.

**Comment by aidarkhanov** [comment]
I updated the library to version 0.7.1 and it works lovely! Thanks for taking time by changing the behavior.

**Comment by samuelgozi** [comment]
No problem, I'm happy to fix it.
BTW, every time you update I recommend looking at the changes since this is still a beta, and stuff can break in every release.
This specific time no breaking changes were made, but I still have some stuff to change before 1.0 that will not be backward compatible.
