### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by dandv** [samuelgozi/firebase-auth-lite#20]
Continuing here the [discussion from the SDK](https://github.com/firebase/firebase-js-sdk/issues/332#issuecomment-625515382), is there a demo I can toy with, to add Apple login? I have a developer account.

**Comment by samuelgozi** [comment]
What kind of demo are you looking for?
I don't have a UI demo I can share. But if you just want to see how to get it working then here is a code example from the docs:

```js
const auth = new Auth({
	apiKey: '[The Firebase API key]',
	redirectUri: 'http://example.com/auth'
});

// This function will run when the user click the sign in button.
function handleSignIn() {
	// This function will redirect the user out of our site, and into
	// the providers auth site. When the user finishes, he will then be
	// redirected into the `redirectUri` we have set in the `auth` instance.
	auth.signInWithProvider('apple.com');
}

// Listen for the click, and run the sign in function.
document.getElementById('sign-in-google').addEventListener('click', handleSignIn);
```

This should work.
But don't forget to authorise the `redirectUri` from the `Auth` options in the Apple login provider settings.

If you got any issues please comment, I'll happily help.

**Comment by samuelgozi** [comment]
Also don't forget to set up sign in with apple in the Firebase console.
But instead of using the URL that firebase suggests(`https://project-name.firebaseapp.com/__/auth/handler`), use the URL that you use in `redirectUri`.

Its completely safe. It actually flows the OpenID standard stricter than what firebase suggests to do(and its also way faster).

**Comment by dandv** [comment]
> What kind of demo are you looking for?

One with social logins, like https://nano-inventory.web.app/

**Comment by samuelgozi** [comment]
@dandv The code I gave you is what the UI in https://nano-inventory.web.app uses(although an older version). The UI itself is not Open Source though.
