### ISSUE TITLE
Get user info from localstorage? / Initial redux state

### ISSUE THREAD

**Issue by tervay** [samuelgozi/firebase-auth-lite#24]
Thanks for making this library.

I have the auth redirect set to `/auth`, and a simple sign in / sign out button; I'm currently using redux-zero as a state management library and am storing whether or not the user is signed in and an identifier in the store; I get this info from the callback passed to `auth.listen`.

However, upon refreshing the page, the store clears, and resets to its initial state (not logged in). However, `firebase-auth-lite` (I believe) knows that the user is currently signed in (and the user data is stored in local storage) (correct me if I am wrong).

Is there a way to access this data from localstorage so that I can set the initial state of the redux store? Apologies if this is already in the API and I've just missed it.

**Comment by samuelgozi** [comment]
Each time constructor runs it checks the local storage and if the user is signed in then all `listen` callbacks are called with the user if it’s logged in or with `null` If he isn’t.

So if you are using `listen` then it should be updated even on refreshes.

Can you please attach the code you use to update the store?

And regardless you can always access the `auth.user` to get the user data, but when working with an external state manger the best solution is to use `listen`, as that’s what’s its intended for.

**Comment by tervay** [comment]
Thanks - I got it working now.

Previously I had set `listen` during render of the auth redirect URI, eg:

```
const AuthRedirect = () => (
    auth.listen( ... );
    auth.handleSignInRedirect();
)
```

Which means listeners weren't getting set properly.

I've moved the `listen` setup to the same time that the store is created:

```
import { auth } from "db"; // the initialized Auth obj from firebase
import createStore from "redux-zero";
import { bindActions } from "redux-zero/utils"

const initialState = { isSignedIn: false, id: null };
const store = createStore(initialState);

const actions = store => ({
    signIn: (state, id) => ({ isSignedIn: true, id }),
    signOut: (state) => ({ isSignedIn: false, id: null })
})

const boundActions = bindActions(actions, store);

auth.listen((user) => {
    if (user === null) {
        boundActions.signOut();
    } else {
        boundActions.signIn(user.localId);
    }
});

export default store;
```

Everything works great now. Thanks for the help.

**Comment by samuelgozi** [comment]
@tervay Got me thinking... A previous feature-request asked to always call a listener function when it is first added, and that could help resolve this mistake. Do you feel like it might be necessary?

**Comment by tervay** [comment]
I think that's one way of mitigating it; I also think something in the docs would help, or an explicit option to enable / disable said behavior.

For example, I previously used `react-google-login` [which had an option for `isSignedIn`](https://www.npmjs.com/package/react-google-login#stay-logged-in) which would then call an `onSuccess` (essentially a `listen`) callback if the user login info was found in local storage.

**Comment by samuelgozi** [comment]
@tervay I don't like the `onSuccess` idea. I mean, it works, and it's flexible, but I think it can be done better. And about the docs. You are right. I didn't update them in a while. I'll get to it.
