### ISSUE TITLE
Is it production ready

### ISSUE THREAD

**Issue by pierrebiver** [samuelgozi/firebase-auth-lite#25]
Hello and thanks for this alternative. I rely on firebase auth using simply email + password and facebook. The full lib is killing my perf. Do you think I could safely switch to yours in prod ?

**Comment by samuelgozi** [comment]
I use it in production, and there are some other people doing so. But it doesn’t work with other official Firebase libs.

Do you use any other Firebase products in your app? If so, then which ones?

**Comment by pierrebiver** [comment]
I just use it for authentication (it's free). Can I use facebook auth ?

**Comment by samuelgozi** [comment]
Yes, you should be ok using it with Facebook and password authentication.
Please let me know if you have any questions as the docs are still not completely up to date.

**Comment by pierrebiver** [comment]
great, thanks for your help 👍
