### ISSUE TITLE
Better to Add Function for Fetching User Data as Optional in Both SignUp and SignIn Methods?

### ISSUE THREAD

**Issue by waleedshkt** [samuelgozi/firebase-auth-lite#30]
I've seen your source code. In that, you are using `fetchProfile` method right after getting auth tokens on successful sign-up or sign-in.

In my view, it'd be better to just remove that function as many times user may require those auth-tokens for further custom authorization.

**Comment by samuelgozi** [comment]
Do you mind giving an example?

**Comment by waleedshkt** [comment]
Let say, you use firebase-auth for user authentication. And let say, Cognito Identity Pool for authorization. So on login/ signup, the auth tokens are required to be passed down to Cognito Identity for getting temporary credentials.

**Comment by samuelgozi** [comment]
Which tokens? The authorization tokens?
And how exactly does the `fetchProfile` affect the flow?
It only refreshes the user data, to keep it up to date.

**Comment by waleedshkt** [comment]
![Screenshot_20200616_210423](https://user-images.githubusercontent.com/26261819/84799067-26348780-b015-11ea-978a-610245fad5f1.jpg)

At (1), you call the actual sign-in method which returns the auth tokens (these ones) you add as input arguments to `fetchProfile` method at (2)

**Comment by samuelgozi** [comment]
I understand where in the code it is created.
My question is; Since I have to retrieve the user data after the user logged in, what would you suggest the alternative be?

And I didn't understand how it affects your authentication flow. Does it throw an error? Or does it stop you from integrating it with Cognito?

**Comment by waleedshkt** [comment]
No it doesn't throw any error. All I'm saying there should be a way to retrieve those tokens along with user data. Right now, it only lets one get user data on authenticating, so yeah one cannot integrate it with service like cognito idenity

May be return a map containing both user-data object as well as tokens?

**Comment by samuelgozi** [comment]
Ohh, got you.
try: `auth.user.tokenManager`, all the tokens should be there except the access token.
