### ISSUE TITLE
Capture Invalid Token id error on creation

### ISSUE THREAD

**Issue by JCWardle** [samuelgozi/firebase-auth-lite#32]
https://github.com/samuelgozi/firebase-auth-lite/blob/ce887d3e7dd7be2337a4f064e89e68caff99819a/src/main.js#L60

I notice the case when the refresh token is invalid is catered for here, but there's also a scenario where the current token is invalid. I think the same behavior should occur for an invalid token as well as an invalid refresh token. That is to return the auth object and signout.

![image](https://user-images.githubusercontent.com/3023731/84966194-3acb6980-b154-11ea-896a-a9c39b9ca903.png)

**Comment by JCWardle** [comment]
This issue seems to be resolved in the latest version. I'm testing it now.

**Comment by samuelgozi** [comment]
Please update if the issue was resolved.

**Comment by JCWardle** [comment]
I've submitted a PR https://github.com/samuelgozi/firebase-auth-lite/pull/34

**Comment by samuelgozi** [comment]
Merged.
