### ISSUE TITLE
User doesn't Sign in Automatically after Signing Up

### ISSUE THREAD

**Issue by waleedshkt** [samuelgozi/firebase-auth-lite#33]
I tried your library. It's super-fast and cool.

Few issues though. Upon registering the user, 
(1) the function doesn't return profile data (is it expected - I checked in `src` file, it does return profile data though?),
(2) adding display name using `updateProfile` method after successful signup returns user-not-sign-in error. Doesn't signup method automatically logins the user?

**Comment by waleedshkt** [comment]
@samuelgozi 
Here is my code:
```
auth.signup(email, pass)
        .then(() => new Promise((resolve, reject) => {
            try {
                auth.updateProfile({ displayName: name });
                resolve();
            }catch(e) {
                reject(e);
            }
        }))
        .then(() => console.log("User account created successfully"))
        .catch(err => console.error(err));
```

I like to promisify things. So on running it, user is signed up but then error of user not logged in pops up when executing `updateProfile` method.

**Comment by samuelgozi** [comment]
first about your code; I'm pretty sure you can write it as follows:
```js
auth.signup(email, pass)
        .then(() =>  auth.updateProfile({ displayName: name }))
        .then(() => console.log("User account created successfully"))
        .catch(err => console.error(err));
```

After that, you can access `auth.user` to see the updated user info.

Your second point sound like a bug. `auth.signup` should indeed log you in.
I'll take a look at it.

**Comment by waleedshkt** [comment]
@samuelgozi, oh cool ,alright.

I didn't know it was an `async` function (makes sense then). I've been referring to api docs though. I believe it's of older version then.

**Comment by waleedshkt** [comment]
@samuelgozi Great. You fixed the issue - I checked the new commit.
But here's an interesting behavior: now the above code executes successfully, and I do call `auth.user` to get user data right after signing up and updating profile with name. 

But that data object doesn't contain `displayName` key. Only after I manually sign in and then call `auth.user` does the name key appears. 

This is a little confusing because now `updateProfile` is getting executed successfully because the user which needs to signed in is so. But the post-fetching of user data doesn't contain the updated name. And I have to manually sign in to retrieve it. So it's like signing in after sign in. Am I being wrong somewhere?
