### ISSUE TITLE
What's the flow for Email Verification?

### ISSUE THREAD

**Issue by waleedshkt** [samuelgozi/firebase-auth-lite#35]
@samuelgozi 

Can you clarify email-confirmation flow?

I call `auth.sendOobCode()` after user successfully signs up. But it throws 
`POST https://identitytoolkit.googleapis.com/v1/accounts:sendOobCode?key=... 400` error followed by 
`INVALID_CONTINUE_URI` error.

**Comment by aidarkhanov** [comment]
Hello! For email verification to work, you have to pass `redirectUri` param to the constructor: `new Auth({ ..., redirectUri: <yourURL> })`.

Usually, `redirectUri` is the home page of your website. Maybe, the desired behavior should be different. For that, I'd like to hear @samuelgozi.

**Comment by waleedshkt** [comment]
@aidarkhanov  
It solved the issue. But I'm not receiving any confirmation email. Strange...

**Comment by samuelgozi** [comment]
@aidarkhanov Thanks! You are right, that how it should be done.
@waleedshkt Please update if something goes wrong.

Email verification works this way:
1. App client(webapp) sends tells the Firebase auth server to generate a code and send it to an email.
2. The server sends that code to the email, with a link back to the app.
3. The app asks the server if the code corresponds to the email.
4. If it is, then the email is verified.

There are some edge cases and some sugar on top of it to make it work seamlessly, but that's the gist of it.
I need to add a verification step that the user has set up a `redirectUri` before using this method.
