### ISSUE TITLE
Firestore rules authentication

### ISSUE THREAD

**Issue by JoshRozin** [samuelgozi/firebase-auth-lite#45]
Hey, loving the package so far. 

It seems the "request.auth" object in Firestore rules is always null when using either the official Firestore SDK and the firebase-firestore-lite along with firebase-auth-lite.

For example, I'm using the rules as follows:

```
match /joins/{joinId}{
      allow read: if true;
      allow create, update: if request.auth.uid == request.resource.data.userId;
      allow delete: if false;
}
```

When I try to create or update this document, I will get a 403 error. Is there anyway we can have some sort of authentication check for Firestore Rules other than using Firebase Cloud Functions?

Thanks so much!

**Comment by samuelgozi** [comment]
Well, without using firebase functions or Firestore rules I don't know of any other way.
Can you please share the requests you are making? It's weird because your rules seem to be fine, so that leads me to believe that something else is modifying the requests.

In order to export all the requests into a HAR file, folow this tutorial:
https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting

Please remove all sensitive information from the HAR file(with a text editor) before sending it.
Or you can just copy-paste the requests here If you'd like.

**Comment by JoshRozin** [comment]
Hey, thanks for getting back to me so quick. 

To clarify, I meant using Firestore rules along with firebase-auth-lite. Here's the request I'm trying to make with both firestore-lite and the official SDK:
```
return firebase
				.firestore()
				.collection("notifications")
				.orderBy("notifiedAt", "desc")
				.where(`notSeen`, "array-contains", userData.credentials.userId)
				.limit(1)
				.onSnapshot((querySnapshot) => {
					if (!querySnapshot.empty) {
						dispatch({
							type: SET_NOTIFICATIONS_SEEN,
							payload: false,
						});
					}
				});
```

`return db
				.ref("notifications")
				.query({
					where: [["notSeen", "contains", userData.credentials.userId]],
					orderBy: { field: "notifiedAt", direction: "desc" },
					limit: 1,
				})
				.run()`

Both result in a 403 error. I've attached the error from the firestore SDK here.
![image](https://user-images.githubusercontent.com/49409991/87231404-fca51c80-c384-11ea-9d62-e8c687dcaf7c.png)

Here's the specific rules for the /notifications category

`match /notifications/{id}{
    	allow read: if request.auth != null;
    	allow create, update, delete: if false;
    }`

The user is signed in because I can make API requests with the token given by:

`user.listen(user => user.tokenManager.idToken);
`

If you still need the HAR file, let me know. 

Thanks again.

**Comment by samuelgozi** [comment]
Oh, now I got you.
This library is not a drop-in replacement for the official one.
You have to use the Firestore companion library.

**Comment by JoshRozin** [comment]
Ah I see, thanks for the help. Anyways, great job with the package. Looking forward to the future of this package and the realtime support of the firestore package.

**Comment by samuelgozi** [comment]
I will update you if I make any progress on the issue.
