### ISSUE TITLE
Support Node env

### ISSUE THREAD

**Issue by universse** [samuelgozi/firebase-auth-lite#48]
Hi there. I'm trying out this library with Next.js and getting this error `SyntaxError: Unexpected token export`.

My current workaround is editing the source file to `module.exports = class Auth {}`.

Happy to open a PR.

**Comment by samuelgozi** [comment]
Hi and thanks for opening an issue.
One of the goals of the library is to run without transpiring on modern browsers and us runtimes(such as deno), this decision was made based on the idea that new browser Use should not be punished.

In other words, replacing the import/export statements to support non standard syntax will force polyfills on newer environments thus making the code slower and not taking advantage of many new optimizations.

I think that polyfills should only be added to target old environments, and not new.

I’m not very familiar with next.js but I would recommend finding a way to tell it’s bundler to also transpire dependencies, this usually solves the issue. I know that some of the users of the lib were able to use it with react native by doing this.

Take a look at closed issues in this library and also in `firebase-firestore-lite` and if you don’t find a solution there, feel free to comment here. I always try to respond ASAP.

**Comment by universse** [comment]
Thank you for your quick and detailed response. I'm dynamically importing the module on client instead, so all is well.
