### ISSUE TITLE
sendOobCode issue

### ISSUE THREAD

**Issue by ochemerys** [samuelgozi/firebase-auth-lite#55]
Hi,

When I use sendOobCode method 

`await auth.sendOobCode('VERIFY_EMAIL', userEmail);`

I have

> Uncaught (in promise) Error: INVALID_CONTINUE_URI
    at eval (main.js?0b3b:129)

or

`await auth.sendOobCode('PASSWORD_RESET', userEmail);`

I have

> Uncaught (in promise) Error: INVALID_CONTINUE_URI
    at eval (main.js?0b3b:129)

or

`await auth.sendOobCode('EMAIL_SIGNIN', userEmail);`

I have

> Uncaught (in promise) Error: OPERATION_NOT_ALLOWED
    at eval (main.js?0b3b:129)

At the same time I'm able to log in and log off and also to make authorizedRequest

I try to use `sendOobCode` to sent request to change password. Documentation does not explain clear the purpose of those request types so I tried them all and none of then worked for me.

Am I doing something wrong or it is a bug there?

Thank you very much.

Oleks Chemerys

**Comment by samuelgozi** [comment]
In regards to the first issue mentioned (the `INVALID_CONTINUE_URI` one), you should pass a `redirectUri` when instantiating the Auth class:
```js
const auth = new Auth({
	apiKey: '[The Firebase API key]',
	redirectUri: 'http://example.com/auth'
});
```

Please let me know if the otter issues do not get resolved.
And add a minimal working example so that I can debug the whole process.

**Comment by ochemerys** [comment]
Thank you, both  scenarios: 1 and 2 are working.
My confusion was that I'm using authentication with email and password and there is no redirectUrl property for auth config related to authentication with email and password in documentation, so I was not aware that it could be required for some specific tasks.
