### ISSUE TITLE
Non-browser support

### ISSUE THREAD

**Issue by ksnyde** [samuelgozi/firebase-auth-lite#57]
An important use case for many Firebase projects is access via serverless and this library seems to depend on localStorage. Ideally you'll want to externalize all aspects like this and let consumers inject storage if needed but right now sadly I can't use this library with AWS Lambda. It's still an important idea ... making Firebase's HTTP API will make their DB's much more usable immediately but it's currently a little brittle to non-core use cases. Good luck with everyhing.

**Comment by samuelgozi** [comment]
Hi and thank you for your feature request. This library doesn't depend on local storage at all and can run on virtually any modern JS environment that supports the Fetch API (or a polyfill of it), for example, it is used by some of my friends React Native. Please look at this issue regarding the local storage alternative:
https://github.com/samuelgozi/firebase-auth-lite/issues/7
