### ISSUE TITLE
User change event emitted before `this.user` updated

### ISSUE THREAD

**Issue by awinograd** [samuelgozi/firebase-auth-lite#8]
https://github.com/samuelgozi/firebase-auth-lite/blob/31754d1141c66624dee79e9a09826a25d8138f39/src/main.js#L148-L152

I think the expected behavior of signOut would be to set `this.user = null;` before calling `this.emit()`

**Comment by samuelgozi** [comment]
You are correct. Feel free to do a pull request if you want.
